# Generated by Django 4.2.17 on 2025-01-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
    ]
