# Generated by Django 5.1.4 on 2025-01-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_remove_ticket_grade_ticket_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='Enviado', max_length=50),
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
    ]
