# Generated by Django 5.1.4 on 2024-12-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_ticket_email_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
    ]
