# Generated by Django 5.1.4 on 2025-01-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_remove_ticket_updated_at_ticket_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='grade',
            field=models.CharField(default='Sin Grado', max_length=50),
        ),
    ]
