# Generated by Django 5.1.4 on 2025-01-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_alter_ticket_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='comments',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
