# Generated by Django 5.1.4 on 2025-01-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_remove_ticket_comments_alter_ticket_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
