# Generated by Django 5.1.4 on 2024-12-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='details',
            field=models.CharField(max_length=255),
        ),
    ]
