# Generated by Django 5.1.4 on 2024-12-16 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Red y Seguridad', 'Red y Seguridad'), ('Sistema de comunicación', 'Sistema de comunicación'), ('Proyección audiovisual', 'Proyección audiovisual'), ('Equipos de informática', 'Equipos de informática'), ('Pantallas digitales', 'Pantallas digitales'), ('Equipos de impresión', 'Equipos de impresión'), ('Enrutadores de red', 'Enrutadores de red')], max_length=100),
        ),
    ]
