# Generated by Django 5.1.4 on 2025-01-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='maintenance_date',
            field=models.DateField(),
        ),
    ]
